pages:
  image: python:3.8
  artifacts:
    paths:
      - public
  script:
    - mkdir -p public
    - pip install jupyter-book
    - jupyter-book build ../handbook
    - mv _build/* public/
  only:
    - main
